/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Esper.Config;
import Events.AuthorizationEvent;
import Events.ClearEvent;
import Events.PanicEvent;
import javax.swing.JButton;
import javax.swing.JProgressBar;
import javax.swing.JTextField;
import javax.swing.JToggleButton;
import static java.lang.Boolean.FALSE;
import static java.lang.Boolean.TRUE;
import javax.swing.JLabel;
import javax.swing.JPasswordField;

/**
 *
 * @author ahmed
 */

public class AlarmGUI extends javax.swing.JFrame {

    /**
     * Creates new form Alarm
     */
    public AlarmGUI() {
        initComponents();
        AuthoizedText.setVisible(false);
    }

//    private Alarm alarm = new Alarm();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Panic = new javax.swing.JButton();
        Clear = new javax.swing.JButton();
        EnterPIN = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        PowerStatus = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BatteryBackup = new javax.swing.JProgressBar();
        MainPowerText = new javax.swing.JLabel();
        MainPower = new javax.swing.JProgressBar();
        BatteryBackupText = new javax.swing.JLabel();
        DoorSensor = new javax.swing.JToggleButton();
        Statuses = new javax.swing.JLabel();
        PinNum = new javax.swing.JPasswordField();
        WindowSensor = new javax.swing.JToggleButton();
        MovmentSensor = new javax.swing.JToggleButton();
        LightSensor = new javax.swing.JToggleButton();
        AuthoizedText = new javax.swing.JLabel();
        Display = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(720, 500));

        Panic.setBackground(new java.awt.Color(123, 15, 15));
        Panic.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        Panic.setForeground(new java.awt.Color(255, 255, 255));
        Panic.setText("Panic protocol");
        Panic.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Panic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PanicActionPerformed(evt);
            }
        });

        Clear.setBackground(new java.awt.Color(51, 153, 0));
        Clear.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        Clear.setForeground(new java.awt.Color(255, 255, 255));
        Clear.setText("Clear");
        Clear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });

        EnterPIN.setBackground(new java.awt.Color(0, 0, 0));
        EnterPIN.setForeground(new java.awt.Color(255, 255, 255));
        EnterPIN.setText("Enter Pin");
        EnterPIN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EnterPIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnterPINActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(238, 238, 238));

        PowerStatus.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        PowerStatus.setText("Power Status");

        BatteryBackup.setForeground(new java.awt.Color(51, 102, 0));
        BatteryBackup.setValue(100);
        BatteryBackup.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        MainPowerText.setText("Main Power");

        MainPower.setForeground(new java.awt.Color(51, 102, 0));
        MainPower.setValue(80);
        MainPower.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        BatteryBackupText.setText("Battery Backup");

        DoorSensor.setBackground(new java.awt.Color(51, 102, 0));
        DoorSensor.setForeground(new java.awt.Color(255, 255, 255));
        DoorSensor.setText("Doors");
        DoorSensor.setEnabled(false);
        DoorSensor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoorSensorActionPerformed(evt);
            }
        });

        Statuses.setText("Statuses");

        PinNum.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PinNum.setRequestFocusEnabled(false);
        PinNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PinNumActionPerformed(evt);
            }
        });

        WindowSensor.setBackground(new java.awt.Color(51, 102, 0));
        WindowSensor.setForeground(new java.awt.Color(255, 255, 255));
        WindowSensor.setText("Windows");
        WindowSensor.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        WindowSensor.setEnabled(false);

        MovmentSensor.setBackground(new java.awt.Color(51, 102, 0));
        MovmentSensor.setForeground(new java.awt.Color(255, 255, 255));
        MovmentSensor.setText("Movment");
        MovmentSensor.setEnabled(false);
        MovmentSensor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MovmentSensorActionPerformed(evt);
            }
        });

        LightSensor.setBackground(new java.awt.Color(102, 0, 0));
        LightSensor.setForeground(new java.awt.Color(255, 255, 255));
        LightSensor.setText("Lights");
        LightSensor.setEnabled(false);

        AuthoizedText.setBackground(new java.awt.Color(0, 0, 0));
        AuthoizedText.setForeground(new java.awt.Color(51, 102, 0));
        AuthoizedText.setText("Authorized personnel");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(MainPowerText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(BatteryBackupText, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(MainPower, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(PinNum, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(AuthoizedText)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BatteryBackup, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PowerStatus))))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(Statuses))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(WindowSensor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(MovmentSensor, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                            .addComponent(DoorSensor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LightSensor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(0, 0, 0)
                .addComponent(jLabel2))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(Statuses, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DoorSensor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(WindowSensor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(MovmentSensor))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(AuthoizedText)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(PinNum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LightSensor)
                        .addGap(12, 12, 12))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(PowerStatus)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(MainPowerText)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(MainPower, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(BatteryBackupText, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(BatteryBackup, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        Display.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Display.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Display.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(EnterPIN, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Panic, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Display, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Display))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Panic, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EnterPIN, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MovmentSensorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MovmentSensorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MovmentSensorActionPerformed

    private void DoorSensorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoorSensorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DoorSensorActionPerformed

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed

        Config.sendEvent(new ClearEvent(TRUE));

    }//GEN-LAST:event_ClearActionPerformed

    private void PanicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PanicActionPerformed

        Config.sendEvent(new PanicEvent(FALSE));

    }//GEN-LAST:event_PanicActionPerformed

    private void DisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DisplayActionPerformed

    private void EnterPINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnterPINActionPerformed
      Config.sendEvent(new AuthorizationEvent(PinNum.getPassword()));
    }//GEN-LAST:event_EnterPINActionPerformed

    private void PinNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PinNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PinNumActionPerformed
    public JToggleButton getDoorBtn() {
        return DoorSensor;
    }

    public JToggleButton getWindowBtn() {
        return WindowSensor;
    }

    public JToggleButton getMovmentBtn() {
        return MovmentSensor;
    }

    public JToggleButton getLightsBtn() {
        return LightSensor;
    }

    public JTextField getDisplayText() {
        return Display;
    }

    public JButton getPanicBtn() {
        return Panic;
    }

    public JButton getClearBtn() {
        return Clear;
    }

    public JProgressBar getMainPowerBar() {
        return MainPower;
    }

    public JPasswordField getPIN() {
        return PinNum;
    }

    public JLabel getAuthorized() {
        return AuthoizedText;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AuthoizedText;
    private javax.swing.JProgressBar BatteryBackup;
    private javax.swing.JLabel BatteryBackupText;
    private javax.swing.JButton Clear;
    private javax.swing.JTextField Display;
    private javax.swing.JToggleButton DoorSensor;
    private javax.swing.JButton EnterPIN;
    private javax.swing.JToggleButton LightSensor;
    private javax.swing.JProgressBar MainPower;
    private javax.swing.JLabel MainPowerText;
    private javax.swing.JToggleButton MovmentSensor;
    private javax.swing.JButton Panic;
    private javax.swing.JPasswordField PinNum;
    private javax.swing.JLabel PowerStatus;
    private javax.swing.JLabel Statuses;
    private javax.swing.JToggleButton WindowSensor;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
